name: camila

models:
  unet:
    encoder_name: timm-efficientnet-b0 # vgg16 # efficientnet-b2
    encoder_weights: 'imagenet'
    activation: 'sigmoid'
    depth: 3
    decoder_channels: [256, 128, 64]
    bottleneck_shape: [3, 9, 9]
    decoder_use_batchnorm: True

  data_unet: # should be the same as unet
    activation: 'sigmoid'
    depth: 3
    decoder_channels: [256, 128, 64]
    bottleneck_shape: [3, 9, 9]
    decoder_use_batchnorm: True
    encoder_type: cnn
    encoder_params:
      bottleneck_shape: [3, 9, 9]
      channels: [ 8, 16, 32]
      kernels: [ 3, 5, 7 ]
    #encoder_type: dense
    #encoder_params:
    #  bottleneck_channels: 1
    # hidden_units: [ 128, 64, 32 ]



dataset:
  path: data/Dataset_One_Circle_1328_128px

test_dataset:
  path: data/Dataset_One_Circle_1328_128px_test

dataloader:
  batch_size: 8
  num_workers: 8
  shuffle: True
  pin_memory: False

test_dataloader:
  batch_size: 8
  num_workers: 1
  shuffle: False
  pin_memory: False


optimizer:
  kwargs:
    lr: 0.0001
    betas: [0.9, 0.999]
    weight_decay: 0.1
    amsgrad: False

train:
  epochs: 1000
  image_size: 128

  log_image_interval: 500
  log_interval: 200
  eval_interval: 500
  save_interval: 50 # is epochs