name: camila

models:
  unet:
    encoder_name: 'vgg16'
    encoder_weights: 'imagenet'
    activation: 'sigmoid'
    depth: 3
    decoder_channels: [512, 256, 128]
    bottleneck_shape: [1, 16, 16]
    decoder_use_batchnorm: True

  data_unet: # should be the same as unet
    activation: 'sigmoid'
    depth: 3
    decoder_channels: [512, 256, 128]
    bottleneck_shape: [1, 16, 16]
    decoder_use_batchnorm: True
    encoder_params:
      bottleneck_channels: 1
      channels: [ 16, 32, 64 ]

dataset:
  path: data/Dataset_One_Circle_1328_128px

test_dataset:
  path: data/Dataset_One_Circle_1328_128px_test

dataloader:
  batch_size: 8
  num_workers: 8
  shuffle: True
  pin_memory: False

test_dataloader:
  batch_size: 8
  num_workers: 1
  shuffle: False
  pin_memory: False


optimizer:
  kwargs:
    lr: 0.0001
    betas: [0.5, 0.999]
    weight_decay: 0.1
    amsgrad: False

train:
  epochs: 500
  image_size: 128

  log_image_interval: 500
  log_interval: 500
  eval_interval: 500
  save_interval: 10 # is epochs