name: camila

models:
  unet:
    encoder_name: 'timm-efficientnet-b1'
    encoder_weights: 'noisy-student'
    activation: 'sigmoid'
    encoder_depth: 4
    decoder_channels: [256, 128, 64, 32]
    bottleneck_channels: 1
    decoder_use_batchnorm: True

dataset:
  path: data/Dataset_One_Circle_1328_128px

dataloader:
  batch_size: 8
  num_workers: 8
  shuffle: True
  pin_memory: False


optimizer:
  kwargs:
    lr: 0.0001
    betas: [0.5, 0.999]
    weight_decay: 0.03
    amsgrad: False

train:
  epochs: 100
  image_size: 128

  log_image_interval: 100
  log_interval: 100
  eval_interval: 100